### ISSUE TITLE
Programming Fundamentals in Swift/Final assessment attempts

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaiOS#1]
![uno](https://user-images.githubusercontent.com/428820/200603154-597ede99-a7ca-4f4b-90f8-b9af300541fe.png)

![dos](https://user-images.githubusercontent.com/428820/200603350-2f0ed6c6-12ee-4787-bcb3-d0e65da1dc8c.png)

![tres](https://user-images.githubusercontent.com/428820/200603656-4988ee45-bca5-47f9-ba38-8b9929eebc0e.png)

**Comment by dennislamcv1** [comment]
They have updated the project and changed the assessment, FYI.
